### ISSUE TITLE
Change logic for directing reports by pro admins to the pro support group 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#7518] opened 2023-01-16 15:46 UTC
Issue:

* Reports of issues relating to public requests, which are suited for the general support mailbox, are being sent to the Pro support address, when the issues are raised by Pros, including Pro admins. 

I suspect an element of this was fixed in the past when all body change requests were routed to the general support mailbox?

There could be different logic applied to Pro admins vs other Pro users. 

Possible new logic:

>If a Pro user is reporting an issue with a public request thread which was not initiated by them then it should be treated as normal and sent to the general support mailbox.

**Comment by garethrees** [comment] 2023-03-28 14:05
Duplicate of https://github.com/mysociety/alaveteli/issues/6704

**Closed by garethrees** 2023-03-28 14:05 UTC
