### ISSUE TITLE
Mark requests as "abandoned"

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#7442] opened 2022-11-20 11:33 UTC
On my dashboard:
![image](https://user-images.githubusercontent.com/11923618/202899608-7f04a8aa-39d6-4df1-8d96-dda1438dcf4f.png)
These are 10 requests that I have given up on, for various reasons. Some go back many years.
![image](https://user-images.githubusercontent.com/11923618/202899644-5a47b314-1a7f-439d-8fb5-8a30f41b099b.png)
I'm obviously not going to be sending follow-ups on those.
It would be good to be able to suppress old requests from such follow-ups. I am aware of the problem of having too many potential request status options, so I hesitate to have an "abandoned"; perhaps the existing "withdrawn" is the closest, but I didn't actually withdraw the request... Perhaps something other than a status to stop prompting for ancient requests?

**Comment by FOIMonkey** [comment] 2022-11-20 12:28
+1 to this. It would come in handy whilst classifying requests that are overdue where confirmation that the information is still wanted has been sought and not received. Technically, these are not requests for clarification and the requests have not been withdrawn. 

It would also be good to be able to hide requests from the Dashboard - I personally had to classify a request made to the Test Quango to make the prompt go away.

**Comment by RichardTaylor** [comment] 2022-11-20 20:32
Closing as a duplicate of https://github.com/mysociety/alaveteli/issues/7067

**Closed by RichardTaylor** 2022-11-20 20:32 UTC
