### ISSUE TITLE
Send reports flagged for admin attention via projects to the pro support address

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/alaveteli#7548] opened 2023-01-25 17:39 UTC
Currently, reports made by people helping to classify requests/extract data using projects are sent to the regular support address, rather than the pro support one. If the request author made the report, then this would be sent to the pro support address as you would expect.

I don't know if this is the right repo for this, as some installs may use a single contact address.

**Comment by garethrees** [comment] 2023-01-25 17:43
Duplicate of https://github.com/mysociety/alaveteli/issues/6704

**Closed by garethrees** 2023-01-25 17:43 UTC
