### ISSUE TITLE
Stop sending alert messages at antisocial hours

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#4903] opened 2018-10-16 13:27 UTC
From WhatDoTheyKnow support mail:

>Can you stop sending me emails at 12.30am

We serve a broad range of users - some of whom might well not expect emails at unusual hours, and they might have their phones or other devices set up to alert them to emails. 

Just passing on the feedback.

**Comment by garethrees** [comment] 2018-10-16 15:40
Marking as a duplicate of https://github.com/mysociety/alaveteli/issues/2747 (though this is the opposite case)

**Closed by garethrees** 2018-10-16 15:40 UTC
