### ISSUE TITLE
report_request generates extraneous output in admin timeline

### ISSUE THREAD

**Issue by mdeuk** [mysociety/alaveteli#5759] opened 2020-06-21 00:50 UTC
When a user makes a report for administrator attention we:
[a] Log this as an event in the request timeline
[b] Log this within Alaveteli's timeline (e.g. /admin/timeline)
[c] Generate an email to the relevant admin/team mailbox

In Alaveteli 0.37.1.2 (e.g. currently running on WDTK) step 'b' is generating extraneous content ("!ruby/object:ActiveRecord::Attribute::FromDatabase name" events) within the admin timeline which is less than desirable as it clogs the admin view, making it more difficult to locate relevant information quickly.
#4965 #5017

**Comment by gbp** [comment] 2020-06-21 09:05
Duplicate of #5699 / #5485

**Closed by gbp** 2020-06-21 09:05 UTC
Labels: bug

**Comment by mdeuk** [comment] 2020-06-21 09:16
> Duplicate of #5699 / #5485

Aha, I hadn't finished writing the report to dev@ for this - thanks for picking it up @gbp 😊
