### ISSUE TITLE
Add ability to leave notes for admins against users/requests

### ISSUE THREAD

**Issue by benrfairless** [mysociety/alaveteli#6225] opened 2021-05-05 04:53 UTC
It would be good to be able to leave admin notes against users and requests, so that a history can be kept of any issues that may arise with a user consistently not following the House Rules.

**Comment by garethrees** [comment] 2021-05-05 11:22
Thanks for the suggestion. Going to close as a duplicate of https://github.com/mysociety/alaveteli/issues/5422.

**Closed by garethrees** 2021-05-05 11:22 UTC
Labels: enhancement, f:admin, x:australia
