### ISSUE TITLE
Ability to create 'signpost' authority pages

### ISSUE THREAD

**Issue by confirmordeny** [mysociety/alaveteli#7369] opened 2022-10-17 21:54 UTC
Add ability to create 'signpost' authority pages that don't allow requests but can point to other authorities. I have suggested something similar to this in the past which was closed but this time I have some specific examples and what I hope is a better reasoning.

My theory is that many people think in terms of buildings, services, brands rather than legal entities. For example, people are more likely to talk about "Thorpe Park" than "Merlin Entertainments Limited". This holds in the public sector also. If I am visiting Chelmsford Library it might not matter which part of local government is running it/funding it. For many the library, leisure centre, museum etc is itself the institution. NHS 111 is a recognised brand.

Examples:
(1) Oban High School is a secondary school in Scotland. We don't list it. I recently discovered from another volunteer that the majority of state schools in Scotland come under the control of the local authority and are not public bodies in their own right in terms of FOISA. You can still request information the school has under FOISA but you need to request it from the local authority. I think this would be far from obvious for most of our current users and potential future users.

(2) We could add individual prisons and then signpost the operator in each case.

(3) Bar Standards Board - might be helpful to list this and point to General Council of the Bar. 

(4) Well known law schools, business schools and medical schools that are technically part of larger institutions.

**Comment by FOIMonkey** [comment] 2022-10-17 22:12
I like the idea. There's definitely a widening participation angle to this. I don't know if there isn't a better way of achieving it using alternative body names somehow, rather than using pages.

**Comment by RichardTaylor** [comment] 2022-10-18 14:30
Duplicate of

* https://github.com/mysociety/alaveteli/issues/7347

**Closed by RichardTaylor** 2022-10-18 14:30 UTC
Labels: user-experience, enhancement, accessibility
