### ISSUE TITLE
Option for multiple request emails for authorities

### ISSUE THREAD

**Issue by gavinrozzi** [mysociety/alaveteli#5488] opened 2019-12-03 19:30 UTC
Several authorities have reached out to the OPRAmachine team inquiring about having the site deliver request emails to multiple addresses at once. This is mainly for the smaller municipalities where requests are primarily delivered to the personal addresses of the records custodians rather than a general OPRA email address for the authority. In some instances, we've seen requests end up getting delayed when those custodians are out of office, but had the request simultaneously been sent to one of the deputy custodian email addresses, they would have been able to respond during the vacation period.

**Comment by garethrees** [comment] 2019-12-06 11:19
We think it's better for citizens if the _authority_ takes on the responsibility of providing a clear FOI contact address. We usually recommend they create `foi@` which then forwards to the pool of responders. Alaveteli handles the responses coming from `person@`, so they don't need anything too complicated on their end.

Closing as a duplicate of https://github.com/mysociety/alaveteli/issues/278.

**Closed by garethrees** 2019-12-06 11:19 UTC
Labels: enhancement, f:authorities, x:new-jersey
