### ISSUE TITLE
Request categorisation review/experiment

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/alaveteli#3013] opened 2016-01-21 16:00 UTC
Should we capture the reason for a request refusal better? 

Our classification is currently ‘successful’, ‘partly successful’ and ‘refused’. 'Refused' doesn't include options of which exemption the request was refused under. 

The Brazilian instance would have found this useful for advocacy purposes apparently. 

Idea: We could ask AccessInfo or another advocacy-type partner their thoughts on this, and whether it would be useful for them.

**Comment by tmtmtmtm** [comment] 2016-01-21 22:06
Previously when we've discussed this in the UK, we've generally believed that the more complex this gets, the more likely it is that people just won't provide the information at all. There's a lot of value in keeping this as simple as possible, even though it would certainly be nice to get more precise information. I also worry that starting to ask people about quite technical things, like which Exemptions were cited, starts pushing this too far into 'scary legal stuff' territory. The question was originally aimed at being as _human_ as possible — many people won't really understand all the seemingly boilerplate gibberish that they get back in their response, they just know whether they got what they asked for or not.

**Comment by skenaja** [comment] 2016-01-26 14:53
#69 is a related issue

**Comment by RichardTaylor** [comment] 2016-02-12 15:36
Per request tags #2302 could be a way of allowing users to mark requests refused for a similar reason and perhaps link to them as a set. 

Request tagging (like tagging a video on YouTube or image on Flickr) could be introduced without any specific purposes and uses of it might emerge. 

We've discussed this before, but perhaps not as far as I can see on a GitHub issue; there are questions like who should be allowed to add/delete tags or do/undo categorisation.

**Comment by garethrees** [comment] 2018-07-20 10:57
Closing as basically a duplicate of #69.

**Closed by garethrees** 2018-07-20 10:57 UTC
Labels: 0 - backlog, enhancement, f:classification
