### ISSUE TITLE
New classifications for appeals to the ICO and Tribunal

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#5281] opened 2019-07-08 17:29 UTC
Reasons in favour:
+ Such classifications could be used by the system to keep requests which are the subject of appeals to the ICO or Tribunal open to new responses longer than usual as responses can come in very late.  
+ Such classifications could enable us to provide tailored advice to requesters.
+ Such classifications could help those browsing the site find interesting material. 

Against:
- Generally we want to keep things simple for most users so avoid having additional classification options.
- Instead of new classifications the issue could be addressed in a more general way by enabling users to tag requests https://github.com/mysociety/alaveteli/issues/2302 but we might still want to prompt users as to what tags to use; and have the system respond to special tags by eg. extending the period before a request is closed. 

Presumably if the system supported appeals to a regulator classification categories as proposed here would be part of such an extension of the system (#2819) but such classification categories might have significant benefit on their own.

**Comment by garethrees** [comment] 2019-07-09 08:42
> Generally we want to keep things simple for most users so avoid having additional classification options.

One thing we could do here is only ever show this as a possibility when a request is in a state that would allow appeal. So maybe you click "refused" and then we list some more options, of which you can then pick "Sent to ICO".

**Comment by mdeuk** [comment] 2019-07-16 18:59
This appears to be broadly related to mysociety/whatdotheyknow-theme#420.

**Comment by garethrees** [comment] 2019-07-17 08:19
Yeah, going to close this as a duplicate of https://github.com/mysociety/whatdotheyknow-theme/issues/420.

Have copied the comments over.

**Closed by garethrees** 2019-07-17 08:19 UTC
Labels: f:classification, improvement, x:uk
