### ISSUE TITLE
Message asking if you are $username appears to signed in users

### ISSUE THREAD

**Issue by robinhouston** [mysociety/alaveteli#389] opened 2012-01-25 13:19 UTC
**[Imported from https://github.com/mysociety/whatdotheyknow/issues/8, reported by dracos on January 12, 2011]**

On other people's accounts, the line is presumably present that is so if you're logged in as someone else, you can switch accounts (shared computer, multiple accounts). I agree this could be better worded, perhaps more along the lines of Amazon's "Not FOO?"?

**Comment by garethrees** [comment] 2018-05-30 10:17
I think this is effectively a duplicate of https://github.com/mysociety/alaveteli/issues/2406, so closing.

**Closed by garethrees** 2018-05-30 10:17 UTC
Labels: 0 - backlog, bug, f:user-profiles, x:uk
