### ISSUE TITLE
Possible bug with missing email list in admin panel

### ISSUE THREAD

**Issue by FOIMonkey** [mysociety/alaveteli#6870] opened 2022-03-09 08:15 UTC
A public authority (https://www.whatdotheyknow.com/admin/bodies/91691) is showing in the list of bodies that have a missing email address on the admin panel despite a valid address having been given.

**Comment by garethrees** [comment] 2022-03-09 09:16
Looks like this is a duplicate of https://github.com/mysociety/alaveteli/issues/4436

**Closed by garethrees** 2022-03-09 09:16 UTC
