### ISSUE TITLE
Ability for non-developer admins to clear caches on specific pages or documents

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6989] opened 2022-04-25 23:20 UTC
Spun out into a specific issue from comments where this is mentioned at:

https://github.com/mysociety/alaveteli/issues/1006#issuecomment-867062203
and
https://github.com/mysociety/whatdotheyknow-theme/issues/588#issuecomment-519531232

When administrating the site it is sometimes highly desirable to be able to remove problematic material straight away. Sometimes there can be serious risks associated with the continued publication of material. 

Having to wait [24 hours in some cases](https://github.com/mysociety/whatdotheyknow-theme/issues/588#issuecomment-519519930) to remove material isn't good.  

Requests to remove material from search engines often can't practically be made until material isn't being served from the site itself. 

Perhaps this could be automated in common cases if making a request "hidden" or "requester_only" automatically cleared relevant caches - for the body and user pages. Mentions of requests on subsequent pages of lists might be more challenging. 

I'm pretty sure the situation in terms of the speed of redactions/removals being reflected on the site didn't used to be as bad as it currently is.

**Comment by FOIMonkey** [comment] 2022-04-26 05:33
+1 This was an issue in a recent case where the request title included a threat. 

> I'm pretty sure the situation in terms of the speed of redactions/removals being reflected on the site didn't used to be as bad as it currently is.

Anecdotally, It does seem to take longer for changes to reflect than was previously the case.

**Comment by garethrees** [comment] 2022-04-26 11:09
There used to be integration with Varnish – the front end cache – but it was removed because it didn't work properly

* https://github.com/mysociety/alaveteli/commit/5ba1c255ce3806b8f010583366185c0b76bb5829
* https://github.com/mysociety/alaveteli/commit/8289904fcfdccaa4289874626c4fe68f3924c5a4
* https://github.com/mysociety/alaveteli/commit/19d7793c11689a558a630a4729ab0a37972be77f

This issue is essentially a duplicate of https://github.com/mysociety/alaveteli/issues/5763, and the fix is https://github.com/mysociety/alaveteli/issues/1475 via https://github.com/mysociety/alaveteli/issues/1006. While I appreciate the issue, I'm going to close this issue as the proposal – effectively a button to "clear cache", or a re-implementation of the varnish purge daemon – is not something we can implement.

**Closed by garethrees** 2022-04-26 11:09 UTC
