### ISSUE TITLE
Malformed incoming messages on request

### ISSUE THREAD

**Issue by MattK1234** [mysociety/alaveteli#6100] opened 2021-02-05 13:29 UTC
Both incoming messages on the WDTK request at https://www.whatdotheyknow.com/request/ipc_grants_11 are malformed and not displayed correctly to the user.

The latter incoming message arrived in the holding pen this morning, and I redirected it. It was malformed in the holding pen too.

This may be duplication of another issue but I couldn't immediately identify one.

**Comment by gbp** [comment] 2021-02-05 13:40
Duplicate of https://github.com/mysociety/alaveteli/issues/5396

**Closed by gbp** 2021-02-05 13:40 UTC
Labels: bug, x:uk
