### ISSUE TITLE
foi_no doesn't prevent message "By law, under all circumstances, AUTHORITY should have responded by now"

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#4499] opened 2018-02-02 15:18 UTC
An example, brought by our attention by the Church Commissioners. 

They are tagged foi_no yet for requests that haven't been responded to, e.g. [this one](https://www.whatdotheyknow.com/request/removal_of_maidstone_borough_cou_10), Alaveteli still states "By law, under all circumstances, Church Commissioners should have responded by now".

That's evidently incorrect: bodies not subject to the FOI Act aren't bound by the section of the FOI act obliging them to respond by a certain date. I'd suggest changing this.

Of course, the moral obligation is a different issue.

**Comment by kingqueen3065** [comment] 2018-02-02 15:31
It also suggests "requesting an internal review" which foi_no bodies are unlikely to have procedures for, particularly if they're not foi_voluntary

**Comment by RichardTaylor** [comment] 2018-02-02 19:14
This is duplicate of #295 - providing another example showing the desirability of fixing the bug - it is also related to #296

**Comment by lizconlan** [comment] 2018-07-24 09:20
Presumably the text "By law, AUTHORITY should normally have responded **promptly**" is similarly unhelpful (appears when overdue rather than very overdue)

**Comment by lizconlan** [comment] 2018-07-24 13:20
### Implementation notes 

The affected text is in `info_request_helper.rb` in `status_text_waiting_response` and `status_text_waiting_response_overdue`. Unless anything else breaks in a full spec, `info_request_helper_spec.rb` looks like the right place to add a couple of new tests to add illustrate the problem.

**Comment by lizconlan** [comment] 2018-07-26 12:39
The relevant tags in use are as follows:

| name | effect | currently supported in core? |
|-------|------|:----:|
| not_apply | marks the authority as not subject to FOI law **and prevents request being made** | Y |
| foi_no       | marks the authority as not subject to FOI law but allows further requests | N |
| foi_voluntary | indicates that the authority is answering requests on a voluntary basis; expected to be use in conjunction with foi_no | N |
| foi_refused | indicates that the authority has indicated that they will not answer requests; expected to be use in conjunction with foi_no | N |

**Comment by lizconlan** [comment] 2018-07-30 10:39
### Relevant status messages

| calculated_state | text | help section |
| ---------------- | ---- | ------------ |
| waiting_response | Currently **waiting for a response** from AUTHORITY, they must respond promptly and normally no later than **RESPONSE_DATE** (details) | quickly_response |
| waiting_response_overdue | Response to this request is **delayed**. By law, AUTHORITY should normally have responded **promptly** and by **RESPONSE_DATE** (details) | quickly_response |
| waiting_response_very_overdue | Response to this request is **long overdue**. By law, under all circumstances, AUTHORITY should have responded by now (details). You can **complain** by requesting an internal. | quickly_response |

**Closed** 2018-08-07 13:56 UTC
Labels: 4 - now, bug, f:request-management, x:uk
