### ISSUE TITLE
Hidden messages are missing padding

### ISSUE THREAD

**Issue by zarino** [mysociety/alaveteli#4407] opened 2017-12-01 10:10 UTC
Not sure whether this is a core thing, an [alavetelitheme](https://www.github.com/mysociety/alavetelitheme) thing, or a [whatdotheyknowtheme](https://www.github.com/mysociety/whatdotheyknowtheme) thing – so feel free to move to a different repo if required!

Looks like `.hidden_message` is missing the `padding: 1.2em` that `.correspondence_text` gets.

![screen shot 2017-12-01 at 10 03 25](https://user-images.githubusercontent.com/739624/33478042-d8ca2d9a-d67f-11e7-8686-b2d876fb4d25.png)

https://www.whatdotheyknow.com/request/compliments_and_complaints_about#incoming-996614

**Comment by garethrees** [comment] 2017-12-01 11:02
Duplicate of https://github.com/mysociety/alaveteli/issues/4407.

I've added some notes to #4407

**Closed by garethrees** 2017-12-01 11:02 UTC
Labels: design
