### ISSUE TITLE
Defunct Authorities Still require email addresses

### ISSUE THREAD

**Issue by benrfairless** [mysociety/alaveteli#1577] opened 2014-06-08 06:43 UTC
When an authority without an email address is tagged as "defunct" the Summary page on admin still insists it needs an email address.

If the authority is defunct, we shouldn't need to collect an email address from it.

**Comment by schlos** [comment] 2020-12-23 21:01
This looks as fixed in 2015 with https://github.com/mysociety/alaveteli/issues/2358.
I tested in v0.33.0.0 and it is not reproducible (it is fixed) - Summary under "Find missing FOI email for these public authorities (try phoning!)" will NOT show defunct bodies that do not have email address.

@garethrees / @gbp could you confirm my findings? If #414 is duplicate then it applies for that also.

**Comment by garethrees** [comment] 2021-01-05 10:49
Yep, looks like this is fixed.

**Closed by garethrees** 2021-01-05 10:49 UTC
Labels: backlog, f:admin, f:authorities, improvement, x:australia

**Comment by garethrees** [comment] 2021-01-05 10:51
> If #414 is duplicate then it applies for that also.

 #414 is to add more special tags similar to `defunct`, so I don't think we'd consider that a duplicate.
