### ISSUE TITLE
Links to pages 21 onwards are broken.

### ISSUE THREAD

**Issue by jlg97** [mysociety/alaveteli#4989] opened 2018-12-04 10:02 UTC
https://www.whatdotheyknow.com/body/bristol_city_council?page=21

https://www.whatdotheyknow.com/body/north_somerset_council?page=21

**Comment by garethrees** [comment] 2018-12-04 12:50
Duplicate of #2137. Sorry 😢 .

**Closed by garethrees** 2018-12-04 12:50 UTC
Labels: bug, f:search, user-experience
