### ISSUE TITLE
Authority version history incomplete

### ISSUE THREAD

**Issue by confirmordeny** [mysociety/alaveteli#8082] opened 2024-01-09 07:33 UTC
I added a test tag to https://www.whatdotheyknow.com/body/dwp today but the version history shows no edits for today or yesterday.

**Comment by garethrees** [comment] 2024-01-09 08:27
I think this is a duplicate of https://github.com/mysociety/alaveteli/issues/1294, though I'm surprised an edit isn't shown at all. I'd expect an empty edit like some of the previous ones:

![Screenshot 2024-01-09 at 08 26 37](https://github.com/mysociety/alaveteli/assets/282788/68d7d552-9e44-4ecf-bc61-b1f9305945ef)

**Comment by garethrees** [comment] 2024-01-09 08:29
Going to close as this is similar enough (if not the same) as https://github.com/mysociety/alaveteli/issues/1294

**Closed by garethrees** 2024-01-09 08:29 UTC
Labels: x:uk, bug, f:authorities, f:admin
