### ISSUE TITLE
Closing brackets at ends of URLs in responses picked up in the href=

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#4168] opened 2017-08-14 18:18 UTC
In https://www.whatdotheyknow.com/request/cfs_pace_permission_to_drop_more#incoming-1001883 a closing bracket has been picked up as the final character of a URL, changing `http://gtr.rcuk.ac.uk/projects?ref=G0200434` to
`http://gtr.rcuk.ac.uk/projects?ref=G0200434)` .

**Comment by garethrees** [comment] 2019-10-30 10:39
This now works.

Looks like this issue may be a duplicate of https://github.com/mysociety/alaveteli/issues/3400

**Closed by garethrees** 2019-10-30 10:39 UTC
Labels: 0 - backlog, bug, f:request-analysis, user-experience, x:uk
