### ISSUE TITLE
Two factor login authentication for all administators and users who opt-in

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#4093] opened 2017-07-08 14:31 UTC
Currently there is an option of two factor authentication for administrators resetting passwords; but there isn't two-factor authentication for every login. 

Related: Increase security of superuser accounts #2697

**Comment by garethrees** [comment] 2017-07-10 08:45
This was by design as we felt that needing a copy of the recovery keys for every login would be pretty annoying, and also insecure as you'd have to carry codes around. SMS works better for this as you only have a valid code on you for 30 seconds or so before you log in.

What's your thinking behind this?

I think using Google Authenticator would make most sense if we wanted to support this, but I don't know what the implication would be for Alaveteli installs in less developed countries.

**Comment by RichardTaylor** [comment] 2017-07-10 15:51
I raised this ticket as a result of noting the the current two-factor authentication system (which protects password resets) with new volunteers and others and observing it's not perhaps what might be expected when one says two factor authentication is a feature the system has.  So I thought I'd add a ticket for discussion of a broader implementation of some form of two factor authentication. 

I agree codes would be a hassle.  Presumably an app or texts would be the way to go.

**Comment by mbimmler** [comment] 2017-07-11 09:56
Ideally I think the system would offer the use of either Google Authenticator or a (flash) SMS... 
Given how widespread mobile phones are even in the Global South, I think the chances of someone who is an Alaveteli super user not having access to a mobile phone that can receive SMS is fairly low - it'd at least be a good fallback if Google Authenticator is not available to someone.

**Comment by garethrees** [comment] 2017-07-11 10:01
RE: SMS, its more that there's an extra cost and complexity burden for partners in setting up a service to handle it.

**Comment by RichardTaylor** [comment] 2021-11-30 19:45
Caution two factor authentication can impact accessibility, see thread 

https://twitter.com/blaine/status/1465726248873648136

It should be OK as an opt-in option though, and for administrators.

**Comment by beedell-roke** [comment] 2024-07-20 13:53
@RichardTaylor, you mention SMS and recovery secrets. You even mention rotating authentication keys. However, instead of Google or Authy's proprietary secrets protocol, have you considered the standardized TOTP specification?

It is commonplace, and operates offline.

**Comment by laurentS** [comment] 2024-11-04 08:31
I think TOTP would be a nice addition when signing in, and definitely for admins (I would enforce this for admins on madada if it were available).

TOTP is indeed usable offline (which isn't terribly useful, as the user needs a connection to alaveteli anyway), and also has the extra advantage of not requiring any additional personal information like a phone number to function. In GDPR countries, this is definitely a plus.
Also it does not require Goolag Authenticator or Authy or any proprietary app.

**Comment by beedell-roke** [comment] 2024-11-04 09:15
@laurentS, I also forgot to mention that CTAP2 (FIDO2) is a more convenient backup option, which fulfils those criteria, too. However, it's not necessarily as portable as TOTP, so both need to be present, if FIDO2 is too.

**Comment by garethrees** [comment] 2024-11-22 12:28
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.

**Closed by garethrees** 2024-11-22 12:28 UTC
Labels: f:user-profiles, enhancement, f:admin

**Comment by beedell-roke** [comment] 2026-08-03 17:12
@garethrees, which 2FA implementation[s] was/were chosen? (I hope CTAP, and/or TOTP!)

**Comment by garethrees** [comment] 2026-08-04 09:44
Authenticator app-based TOTP; might look at passkeys down the line as that seems to be where things are heading.
