### ISSUE TITLE
Users can't replace user photo

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#4477] opened 2018-01-24 16:46 UTC
Attempting to replace a user photo results in the original photo still being displayed. 

Clearing the photo does clear the photo but then uploading a new photo results in the original photo being displayed again. 

Bug reported by user of WhatDoTheyKnow.com and confirmed by me.

**Comment by RichardTaylor** [comment] 2018-01-26 13:39
On checking a day or so later after trying to update the image the new image was present, suggesting a caching issue.

**Comment by garethrees** [comment] 2018-01-29 09:37
Here's a [link](https://groups.google.com/a/mysociety.org/forum/#!topic/alaveteli/cEhB9Jla7fY) to the specific case.

Does indeed sound like a caching issue.

**Comment by garethrees** [comment] 2018-05-30 10:11
Duplicate of https://github.com/mysociety/alaveteli/issues/156.

**Closed by garethrees** 2018-05-30 10:11 UTC
Labels: 0 - backlog, bug, f:user-profiles, user-experience, x:uk
