### ISSUE TITLE
Spreadsheet import: source of contact data

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#4077] opened 2017-07-02 16:06 UTC
When we add or update an authority, we put the source for the contact details we've used in the "Comment for this edit" section. The "add authority" form for use by users asks for the source for the details also and autopopulates that field.

There's no option to include this in the "import spreadsheet" system, which means such isn't captured. It would be great if it was.

**Comment by garethrees** [comment] 2018-05-30 09:02
Duplicate of https://github.com/mysociety/alaveteli/issues/3719

**Closed by garethrees** 2018-05-30 09:02 UTC
Labels: 0 - backlog, easier-admin, f:admin, f:authorities, framework-improvement, improvement, x:uk
