### ISSUE TITLE
[ERROR] admin_general#stats (NoMethodError) "undefined method `each' for 406888:Fixnum"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4015] opened 2017-06-01 09:56 UTC
```
A NoMethodError occurred in admin_general#stats:

  undefined method `each' for 406888:Fixnum
  app/views/admin_general/stats.html.erb:24:in `_app_views_admin_general_stats_html_erb__3236303781571013909_100518660'

-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/admin/stats
  * HTTP Method: GET
  * IP address : FILTERED
  * Parameters : {"controller"=>"admin_general", "action"=>"stats"}
  * Timestamp  : 2017-05-19 11:56:05 +0100
  * Server : FILTERED
  * Rails root : /FILTERED/www.whatdotheyknow.com/alaveteli-2017-05-19T10-45-40
  * Process: 32007

-------------------------------
Backtrace:
-------------------------------

  app/views/admin_general/stats.html.erb:24:in `_app_views_admin_general_stats_html_erb__3236303781571013909_100518660'
  app/controllers/application_controller.rb:108:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'

```

**Comment by garethrees** [comment] 2017-06-01 09:56
This came through on 19th May and still appears to be an issue.

**Comment by lizconlan** [comment] 2017-06-01 10:32
duplicate of #3984

**Closed by lizconlan** 2017-06-01 10:32 UTC
Labels: 1 - new, bug
