### ISSUE TITLE
[ERROR] AdminUserController#edit (NoMethodError) undefined method `can_admin_role?' for nil:NilClass

### ISSUE THREAD

**Issue by gavinrozzi** [mysociety/alaveteli#4104] opened 2017-07-15 16:39 UTC
Clicking the "Edit" button on a user profile from the admin interface produces a NoMethodError.
I have reproduced this error on fresh installs on both Ubuntu Trusty and Debian Jessie, in both production and staging modes.
The full error message is as follows:
```
undefined method `can_admin_role?' for nil:NilClass

Extracted source (around line #35):

          
33                            role.id,
34                            @admin_user.roles.include?(role),
35                            :disabled => !@user.can_admin_role?(role.name.to_sym) %>
36          <% if !@user.can_admin_role?(role.name.to_sym) &&
37             @admin_user.roles.include?(role) %>
38            <%= hidden_field_tag "admin_user[role_ids][]",                   

Rails.root: /var/www/FILTERED/alaveteli

Application Trace | Framework Trace | Full Trace
app/views/admin_user/_form.html.erb:35:in `block in _app_views_admin_user__form_html_erb___2568025543175684676_104228440'
app/views/admin_user/_form.html.erb:29:in `_app_views_admin_user__form_html_erb___2568025543175684676_104228440'
app/views/admin_user/edit.html.erb:4:in `block in _app_views_admin_user_edit_html_erb__3416695520976812754_104208800'
app/views/admin_user/edit.html.erb:3:in `_app_views_admin_user_edit_html_erb__3416695520976812754_104208800'
app/controllers/application_controller.rb:113:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'
Request

Parameters:

{"id"=>"3"}
Toggle session dump
Toggle env dump
Response

Headers:

None
```

**Comment by garethrees** [comment] 2017-07-17 08:50
Have you run `bundle exec rake db:seed`? This hasn't yet been added to the install script (#4029) so this might be caused by not having any roles and user to role mappings.

**Comment by garethrees** [comment] 2017-07-25 11:14
I can't seem to reproduce this.

What commit did you have checked out?

You can get this by running `git show | grep commit` in the alaveteli directory.

**Comment by gavinrozzi** [comment] 2017-07-25 14:25
commit fc83ca1ab0074b925a3b0107c42bce4f0edc2693

**Comment by gavinrozzi** [comment] 2017-08-09 19:18
bundle exec rake db:seed results in an error 
```
gavin@localhost:/var/www/opramachine.com/alaveteli$ bundle exec rake db:seed
Rails Error: Unable to access log file. Please ensure that /var/www/opramachine.com/alaveteli/log/development.log exists and is chmod 0666. The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
No database tables found for feature flags, you might need to set a backend explicitly if you don't want them stored in a database, or runrake db:migrate to create the table.
Using memory-based feature storage instead.
rake aborted!
PG::ConnectionBad: FATAL:  Peer authentication failed for user "alaveteli"
/home/alaveteli/bundle/ruby/2.1.0/gems/activerecord-4.1.16/lib/active_record/connection_adapters/postgresql_adapter.rb:888:in `initialize'
/home/alaveteli/bundle/ruby/2.1.0/gems/activerecord-4.1.16/lib/active_record/connection_adapters/postgresql_adapter.rb:888:in `new'
/home/alaveteli/bundle/ruby/2.1.0/gems/activerecord-4.1.16/lib/active_record/connection_adapters/postgresql_adapter.rb:888:in `connect'
/home/alaveteli/bundle/ruby/2.1.0/gems/activerecord-4.1.16/lib/active_record/connection_adapters/postgresql_adapter.rb:568:in `initialize'
/home/alaveteli/bundle/ruby/2.1.0/gems/activerecord-4.1.16/lib/active_record/connection_adapters/postgresql_adapter.rb:41:in `new'
/home/alaveteli/bundle/ruby/2.1.0/gems/activerecord-4.1.16/lib/active_record/connection_adapters/postgresql_adapter.rb:41:in `postgresql_connection'
/home/alaveteli/bundle/ruby/2.1.0/gems/activerecord-4.1.16/lib/active_record/connection_adapters/abstract/connection_pool.rb:435:in `new_connection'
/home/alaveteli/bundle/ruby/2.1.0/gems/activerecord-4.1.16/lib/active_record/connection_adapters/abstract/connection_pool.rb:445:in `checkout_new_connection'
/home/alaveteli/bundle/ruby/2.1.0/gems/activerecord-4.1.16/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `acquire_connection'
/home/alaveteli/bundle/ruby/2.1.0/gems/activerecord-4.1.16/lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in `block in checkout'
/home/alaveteli/bundle/ruby/2.1.0/gems/activerecord-4.1.16/lib/active_record/connection_adapters/abstract/connection_pool.rb:350:in `checkout'
/home/alaveteli/bundle/ruby/2.1.0/gems/activerecord-4.1.16/lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in `block in connection'
/home/alaveteli/bundle/ruby/2.1.0/gems/activerecord-4.1.16/lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection'
/home/alaveteli/bundle/ruby/2.1.0/gems/activerecord-4.1.16/lib/active_record/connection_adapters/abstract/connection_pool.rb:541:in `retrieve_connection'
/home/alaveteli/bundle/ruby/2.1.0/gems/activerecord-4.1.16/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/home/alaveteli/bundle/ruby/2.1.0/gems/activerecord-4.1.16/lib/active_record/connection_handling.rb:87:in `connection'
/home/alaveteli/bundle/ruby/2.1.0/gems/activerecord-4.1.16/lib/active_record/migration.rb:916:in `initialize'
/home/alaveteli/bundle/ruby/2.1.0/gems/activerecord-4.1.16/lib/active_record/migration.rb:829:in `new'
/home/alaveteli/bundle/ruby/2.1.0/gems/activerecord-4.1.16/lib/active_record/migration.rb:829:in `open'
/home/alaveteli/bundle/ruby/2.1.0/gems/activerecord-4.1.16/lib/active_record/railties/databases.rake:157:in `block (2 levels) in <top (required)>'
/home/alaveteli/bundle/ruby/2.1.0/gems/activerecord-4.1.16/lib/active_record/railties/databases.rake:173:in `block (2 levels) in <top (required)>'
/home/alaveteli/bundle/ruby/2.1.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:abort_if_pending_migrations
(See full trace by running task with --trace)
```

**Comment by garethrees** [comment] 2017-08-14 11:01
I've had a bit more of a dig in to this, but still can't reproduce the original error.

What process did you go through to install the site? Did you use Vagrant, or are you installing on to some cloud server by running the script? What arguments did you provide to the script if so?

How did you create the users you're trying to edit? Manually, through the console, or with `script/load-sample-data`?

The error you can see running `rake db:seed` looks like its because of some permissions errors:

> `Rails Error: Unable to access log file. Please ensure that /var/www/opramachine.com/alaveteli/log/development.log exists and is chmod 0666. The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.`

and

> `PG::ConnectionBad: FATAL:  Peer authentication failed for user "alaveteli"`


What system user is alaveteli installed as? By default its' `alaveteli`, but you're running `bundle exec rake db:seed` as `gavin`. You should run the commands as the app user e.g. `gavin@localhost:/var/www/opramachine.com/alaveteli$ sudo -u alaveteli bundle exec rake db:seed`

If you provide the full steps you took to install I can run them here and try to get to the same point that you're at.

**Comment by gavinrozzi** [comment] 2017-08-24 17:11
I had the app installed under the user gavin previously. I reinstalled and made the account with the username alaveteli and installed it under that on a fresh server just to be safe. With that done, I was able to run bundle exec rake db:seed with no issues and I have it running in production mode. But whenever I attempt to edit any user, whether it's an account I registered or the internal admin user, I receive this same error. Even with no customizations and the default alaveteli theme.

**Comment by garethrees** [comment] 2017-09-06 16:28
Hey @gavinrozzi – sorry its been a while getting back to you. What arguments did you run the install script with?

**Comment by garethrees** [comment] 2017-09-06 17:37
And which OS?

**Comment by handelaar** [comment] 2017-11-14 00:59
Upgraded foi.ie dev site --> this exact problem. Seeding roles has no discernable effect. Additionally, it became impossible following upgrade to log in to admin at all because upgrade migrations deleted the admin column on the user table, while also creating no new admin role, and nothing at all in users_roles.

Now: cannot edit a user, cannot log into admin except with emergency user.

**Comment by handelaar** [comment] 2017-11-14 01:40
(Update: prob is with emergency user.  I manually set up users_roles entries with direct sql queries, logged out, logged back in as an actual user, and the 500 error on user edit no longer appeared. However, it's not possible to select pro or pro_admin on the edit page when editing myself.)

**Comment by garethrees** [comment] 2017-11-14 09:24
Hey @handelaar,

The [problem](https://groups.google.com/d/msg/alaveteli-dev/SpCdpphGnjs/81d9nBp4BgAJ) in Gavin's case was that there were no `roles` or `users_roles` mappings.

> Adding roles can be solved by running `RAILS_ENV=production bundle exec rake db:seed`.
> 
> To map an admin role to your user, you'll need to dive in to the rails console, which can be run with `RAILS_ENV=production bundle exec rails console`.
> 
> You can then find your user and add the correct role:

>     User.find_by(name: 'Gavin Rozzi').add_role(:admin)

> Once you've done that, you should be set.

There's also a `bundle exec rake temp:migrate_admins_and_pros_to_roles` task, that needed to be run in 0.29.0.0. This task won't work on 0.30.0.0, as the deprecated `User#admin_level` attribute has been removed.

**Comment by handelaar** [comment] 2017-11-14 13:53
What you're saying there is a migration that's required when moving from pre-0.29 to 0.30 is not called on upgrade.

**Comment by garethrees** [comment] 2017-11-15 12:00
We're not _totally_ clear on what's happening here, as we haven't experienced the issue when upgrading any production sites that we run.

Here's my current understanding:

* `bundle exec rake db:seed` needed to be run when upgrading to [`0.29.0.0`](https://github.com/mysociety/alaveteli/releases/tag/0.29.0.0). This adds the default `roles` to the database.
* `bundle exec rake temp:migrate_admins_and_pros_to_roles` needed to be run when upgrading to [`0.29.0.0`](https://github.com/mysociety/alaveteli/releases/tag/0.29.0.0). This gives each admin an `admin` role, in preparation for the removal of the old `admin_level` attribute.
* [`0.30.0.0`](https://github.com/mysociety/alaveteli/releases/tag/0.30.0.0) drops the `admin_level` attribute. We make it clear that you need to have run the above steps from the `0.29.0.0` release before upgrading.

For new installs:

* `db:seed` doesn't get called in the install script (https://github.com/mysociety/alaveteli/issues/4029), so it won't have the roles. If you install 0.30.0.0, running `db:seed` and then `temp:migrate_admins_and_pros_to_roles` won't work, because there's no `admin_level` attribute to migrate from.
* If you're installing `0.29.0.0`, `db:seed` doesn't get called, but running that and then `temp:migrate_admins_and_pros_to_roles` _should_ work, as the `admin_level` attribute still exists at that point.

For upgrades:

* Not totally sure why this breaks if you follow the upgrade steps. 
* If the `0.29.0.0` upgrade steps were missed the migration tasks wouldn't work as explained above, due to `admin_level` being removed in `0.30.0.0`.

---

> What you're saying there is that a migration that's required when moving from pre-0.29 to 0.30 is not called on upgrade, and that this removes all admins from an existing Alaveteli.

The data migrations are manual steps that must be run.

> And that one row in the 'roles' table without which the site can't function any more is also not added by any migrations during upgrade.

Running `db:seed` is also a manual step.

> However, it's not possible to select pro or pro_admin on the edit page when editing myself.

Pro isn't really ready for reuse yet. This is intentional, as we're manually handling `pro` and `pro_admin` abilities on WDTK for now.

You can add these roles in the console, though, with something like:

```ruby
user = User.find(USER_ID)
user.add_role(:pro)
user.add_role(:pro_admin)
```

> prob is with emergency user

I've only had a quick scan, but yeah, it does look like this doesn't really work with the roles system.

---

Diving in to this isn't at the top of our list at the moment I'm afraid. We'd totally welcome contributions to fix the issue in the meantime though.

**Comment by handelaar** [comment] 2017-11-15 14:08
It's slightly moot now all round, I think (though perhaps leave this up because it'll smack *all* the other sites that haven't done this upgrade yet), but let's be clear about something:

>> What you're saying there is that a migration that's required when moving from pre-0.29 to 0.30 is not called on upgrade, and that this removes all admins from an existing Alaveteli.

>The data migrations are manual steps that must be run.

When?  Before the upgrade, when they'll fail because the table doesn't exist yet? Or after the upgrade, when the admins have already been deleted?

:)

And as it turns out, the entire thing with roles isn't what causes the error that's actually mentioned in the title of this issue. **At all.** The fact that the Emergency User can't *do* any of the things to create an admin level user as documented in the 'next steps after install' docpage causes it.

**Comment by lizconlan** [comment] 2019-03-21 16:41
Looks like the emergency user stopped being able to function as an admin when we moved to relying on roles and abilities via `can?`

**Comment by garethrees** [comment] 2019-03-25 16:07
Probably should do https://github.com/mysociety/alaveteli/issues/810 to deprecate the emergency user.

**Comment by garethrees** [comment] 2020-12-01 09:58
Going to close this as the bug is tracked in https://github.com/mysociety/alaveteli/issues/5604.

**Closed by garethrees** 2020-12-01 09:58 UTC
Labels: backlog, bug, f:admin
