### ISSUE TITLE
Canned response for closing new body and body change requests

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6904] opened 2022-03-25 10:06 UTC
Messages can be sent via the system to close requests to add, or update, a public body. 

Currently admins are faced with a blank free-text box. 

This could be usefully pre-filled with a canned response, and signature. 

Content for such canned responses could be collated from previous manually listed responses.

**Comment by RichardTaylor** [comment] 2022-03-25 11:34
There's a non-developer / admin sub-task here of proposing text for the canned responses.

**Comment by RichardTaylor** [comment] 2022-04-25 17:07
Draft for closing (rejecting) a add body request below. 

Often we provide quite specific and tailored advice/research/commentary in these cases. But the template would still be a good start.  

>Thanks for the suggestion but we only list public bodies on WhatDoTheyKnow (or organisations which have roles which would otherwise be carried out by public bodies).
>
>This organisation doesn't appear to be a public body, and doesn't appear to be subject to FOI or similar laws so we have decided not to list it. 
>
>Details of our criteria for listing organisations can be found at:
>
>https://www.whatdotheyknow.com/help/requesting#authorities
>
>
>If you think we've made the wrong decision, for example if you think the body is subject to FOI, or has a role which means it should be subject to FOI, do reply and let us know, explaining the situation, providing links to support the case you are making. 
>
>You may be able to obtain the information you are seeking by making your request to a public body involved in the activities you are interested in. For example if a public body funds, or contracts, the body in question you could seek information about that funding or contract and how it is monitored, from the public body. 
>
>Charities are not automatically public bodies. You may be able to find some information about them from on the Charity Commission register https://register-of-charities.charitycommission.gov.uk/ 
>
>If all a body's members are public bodies then it is itsself be subject to FOI, and we would list it. If this is the case here do let us know.
>

**Comment by garethrees** [comment] 2022-05-19 08:32
I think this is a duplicate of https://github.com/mysociety/alaveteli/issues/4644 and https://github.com/mysociety/alaveteli/issues/6731?

**Comment by RichardTaylor** [comment] 2022-05-19 10:14
This is a duplicate of #4644 

The ticket a #6731 proposes an additional canned response for this form to use in a different situation - for misuse of the form. 

At https://github.com/mysociety/alaveteli/issues/6731#issuecomment-1130404994 William has noted another situation which might warrant - where a body is already listed. Very closely related is the situation where someone asks for part of an organisation to be listed, or for a service to be listed, and we point them to an existing body on our site.

**Comment by garethrees** [comment] 2022-05-19 14:19
Thanks for clarifying!

Closing as a duplicate of https://github.com/mysociety/alaveteli/issues/4644.

**Closed by garethrees** 2022-05-19 14:19 UTC
Labels: x:uk, easier-admin, improvement, f:admin
