### ISSUE TITLE
Document building translations for a theme

### ISSUE THREAD

**Issue by stevenday** [mysociety/alaveteli#3122] opened 2016-03-24 11:50 UTC
I think I need to run:

```shell
$ bundle exec rake gettext:find_theme THEME=mytheme-name
```

But I only figured this out by poking around in `lib/tasks`. http://alaveteli.org/docs/developers/i18n/ and http://alaveteli.org/docs/customising/themes/ don't make any mention of it.

**Comment by garethrees** [comment] 2016-03-24 12:20
Dupe of https://github.com/mysociety/alaveteli/issues/3122

**Comment by garethrees** [comment] 2016-03-24 12:21
Edited with correct issue!

**Closed by garethrees** 2016-03-24 12:20 UTC

**Comment by stevenday** [comment] 2016-03-24 12:23
D'oh, I thought I'd had this issue before but I couldn't find it, sorry!

**Comment by garethrees** [comment] 2016-03-24 12:24
No problem! The link back to the original is a good pointer that its come up again, anyway :)
