### ISSUE TITLE
Review presentation of categorisation game

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#4941] opened 2018-11-05 16:06 UTC
A prospective volunteer has shared their first impressions of:

https://www.whatdotheyknow.com/categorise/play

They questioned the "play" language, suggesting it made the task appear unimportant or even "not real" - saying they wondered if the "game" was actually a live part of the system. 

They also suggested there should be more guidance for categorising requests eg. what to do if part of a request is refused, but part is successful.

**Comment by garethrees** [comment] 2022-02-15 11:44
I think this is essentially a duplicate of https://github.com/mysociety/alaveteli/issues/1566 – not very clear to new users.

**Closed by garethrees** 2022-02-15 11:44 UTC
Labels: x:uk, f:classification, improvement
