### ISSUE TITLE
Prevent non-logged in users suggesting new bodies, or suggesting body request_address changes

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#7476] opened 2022-12-16 19:43 UTC
Reasons for:

* Reduce junk / spam submissions 

Reasons against:

* We want to make it easy and friction-free for eg. officers at public bodies to suggest changes.

**Comment by garethrees** [comment] 2022-12-19 10:37
Closing as duplicate of https://github.com/mysociety/alaveteli/issues/5957

**Closed by garethrees** 2022-12-19 10:37 UTC
Labels: x:uk, reduce-spam, f:authorities, improvement, reduce-admin
