### ISSUE TITLE
Automatic email redaction may be corrupting some email-heavy files

### ISSUE THREAD

**Issue by gavinrozzi** [mysociety/alaveteli#4357] opened 2017-11-12 20:52 UTC
A recent request on opramachine.com (latest version of Alaveteli) appears to be having an issue with file corruption related to the automatic redaction of email addresses done by Alaveteli on the site.

URL of the request: https://opramachine.com/request/email_logs_for_george_snyder

In the request, I requested documents known as "email logs" which are essentially just a printout of a fields of data from a public official's email inbox. Two of the fields included lists of each email address involved in the chain of correspondence, which I am assuming was picked up by the email auto-redaction.

When I download the Excel (.xls) file provided by the municipality in above request from the frontend Alaveteli URL, the Excel file is corrupted and cannot be opened. To rule out the possibility that the authority sent a corrupt file, I asked the records custodian (FOI officer) to re-send the responsive file just to be sure. After attempting to access the second Excel file, it still wouldn't open.

I was able to open up the document once I downloaded a copy of the raw email using the admin interface and opened it using my regular email program on my PC and open the Excel file from there using the attachment interface. That version of the file opened up in Excel without issue, so I am assuming it was the email address auto redaction that may have played a role in corrupting the file since it consisted of numerous email addresses.

**Comment by garethrees** [comment] 2017-11-13 09:21
Hey Gavin,

Yeah, we're having a bit of a problem with this on WhatDoTheyKnow as well.

You've done exactly the right thing to work around it – we tend to then upload the file (e.g. Google Drive, Dropbox, etc. We use `files.whatdotheyknow.com`) and add an annotation with a URL to it, explaining what has happened.

Looking in to this is on our immediate list of priorities, so going to close this as a duplicate of https://github.com/mysociety/alaveteli/issues/3233. I've noted that you've been hit by this issue too.

**Closed by garethrees** 2017-11-13 09:21 UTC
