### ISSUE TITLE
[ERROR] admin_general#index (NoMethodError) "undefined method `in_time_zone' for nil:NilClass"

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4119] opened 2017-07-24 10:21 UTC
```
 NoMethodError occurred in admin_general#index:

  undefined method `in_time_zone' for nil:NilClass
  app/helpers/date_time_helper.rb:39:in `simple_date_html'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/admin
  * HTTP Method: GET
  * IP address : FILTERED
  * Parameters : {"controller"=>"admin_general", "action"=>"index"}
  * Timestamp  : 2017-07-20 18:48:19 +0100
  * Server : FILTERED
  * Rails root : /FILTERED/www.whatdotheyknow.com/alaveteli-2017-07-19T14-30-12
  * Process: 16332

-------------------------------
Backtrace:
-------------------------------

  app/helpers/date_time_helper.rb:39:in `simple_date_html'
  app/helpers/date_time_helper.rb:26:in `simple_date'
  app/views/admin_general/_to_do_list.html.erb:44:in `block in _app_views_admin_general__to_do_list_html_erb__3233611733368976305_81339260'
  app/views/admin_general/_to_do_list.html.erb:15:in `_app_views_admin_general__to_do_list_html_erb__3233611733368976305_81339260'
  app/views/admin_general/index.html.erb:164:in `_app_views_admin_general_index_html_erb__1225036248724457455_81206380'
  app/controllers/application_controller.rb:108:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by garethrees** [comment] 2018-10-08 11:46
Duplicate of https://github.com/mysociety/alaveteli/issues/4326

(This issue is older, but the newer one has a bit more detail so favouring that one).

**Closed by garethrees** 2018-10-08 11:46 UTC
Labels: 0 - backlog, bug, f:admin, x:uk
