### ISSUE TITLE
Users with duplicate names probed on logging in

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#3030] opened 2016-01-27 22:13 UTC
Where two or more users have the same names, when they log in they're given the "did you mean the other user X" prompt. This prompt is helpful elsewhere, where there is more than one user with the same name, but makes no sense in this context.

![wdtk](https://cloud.githubusercontent.com/assets/11923618/12630194/3a97df4a-c543-11e5-8157-110728eccc4a.jpg)

**Comment by garethrees** [comment] 2016-01-29 22:45
I think this might be a dup of https://github.com/mysociety/alaveteli/issues/3030

**Comment by kingqueen3065** [comment] 2016-01-29 23:17
this is #3030 Gareth :-)

**Comment by garethrees** [comment] 2016-01-29 23:20
Oops! Shows I shouldn't be looking at GitHub on a Friday night. I meant https://github.com/mysociety/alaveteli/issues/389

**Comment by kingqueen3065** [comment] 2016-01-30 00:42
:-) I'm not sure it is the same issue; it's difficult without the context of the older issue, but that appears to be if a communal computer has more than one user, rather than if our system has another user of the same name? I.e. instead of "you're Mark, did you not mean to log in as Jane who also logs into this computer?" (which is what I *think* that issue's about) it's "you're Douglas Paulley of Wetherby, are you sure you didn't mean to log in as Douglas Paulley of Thurso?" - the latter is the behaviour the user is commenting on.

**Comment by garethrees** [comment] 2018-05-30 10:18
Closing as a duplicate of https://github.com/mysociety/alaveteli/issues/2406

**Closed by garethrees** 2018-05-30 10:18 UTC
Labels: 0 - backlog, f:user-profiles, improvement, user-experience, x:uk
