### ISSUE TITLE
GitHub Pages: Navigation broken in subpages

### ISSUE THREAD

**Issue by wfdd** [mysociety/alaveteli#4130] opened 2017-08-01 12:27 UTC
Nav bar links are resolved relative to the current page, so when you're on, e.g. 'Sites' (http://alaveteli.org/deployments/), clicking on 'Sites' again will take you to http://alaveteli.org/deployments/deployments/.  This is probably a regression (maybe jekyll/jekyll#6057).

**Comment by garethrees** [comment] 2017-08-01 14:06
Hey @wfdd, thanks for reporting.

We're aware of this (https://github.com/mysociety/alaveteli/issues/4109) and we're aiming to get it fixed soon.

Closing as a duplicate of #4109.

**Closed by garethrees** 2017-08-01 14:06 UTC
