### ISSUE TITLE
Odd formatting on body description on writing page

### ISSUE THREAD

**Issue by ajparsons** [mysociety/alaveteli#7410] opened 2022-11-02 16:03 UTC
Public body descriptions get oddly nested when not logged in (or non pro view)?

Not logged in:

![image](https://user-images.githubusercontent.com/8157058/199540012-118114a6-9f22-4e47-82bd-4cc77acb8cc6.png)

Logged in:

![image](https://user-images.githubusercontent.com/8157058/199539871-bda44349-80e1-4f34-977f-8b1eca7b680d.png)

**Comment by garethrees** [comment] 2022-11-02 16:58
Closing as a duplicate of https://github.com/mysociety/whatdotheyknow-theme/issues/1411. Thanks for reporting!

**Closed by garethrees** 2022-11-02 16:58 UTC
