### ISSUE TITLE
Add a "view members of this category" list to the category edit page

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#7177] opened 2022-07-20 14:48 UTC
eg. at 

https://www.whatdotheyknow.com/admin/categories/103/edit

include at link to

https://www.whatdotheyknow.com/body/list/inns_of_court

**Comment by gbp** [comment] 2022-07-20 14:53
Duplicate of #7087 - although I was thinking linking to the admin authority search rather than the public one.

**Closed by gbp** 2022-07-20 14:53 UTC
Labels: easier-admin
