### ISSUE TITLE
Some users confused by email address redaction

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#4322] opened 2017-10-26 12:56 UTC
Some users of WhatDoTheyKnow (both requesters and FOI officers) are confused by the automatic redaction of email addresses from correspondence. 

Some users don't follow the link in the replacement text of "[[email address](https://www.whatdotheyknow.com/help/officers#mobiles)]" to find our advice. 

Problems arise, for example, when public bodies try to refer a user to another body, and offer its email address.

For an example of typical confusion see:
https://www.whatdotheyknow.com/request/translation_services_9#incoming-474975

Ideas:
* Offer some advice on mouse-over of the removed address (not good for mobile though).
* Detect other bodies' request addresses and offer a link to them (gets into the realm of editing the response from the public body though).
* In any advice to public bodies suggest referrals to other bodies include a link to the body on our site rather than an email address (we've just suggested this to one FOI officer by email and they said they'd do it!). 
* One FOI officer assumed users got a copy of their response in full by email; perhaps consider if our advice / help pages ought make clear that doesn't happen (probably not needed unless this is a widespread assumption). 

Related: #10

**Comment by 12johnsonf** [comment] 2017-10-30 23:01
Stick emails behind a reCAPTCHA?

**Comment by RichardTaylor** [comment] 2018-03-25 02:27
A confused user corresponded directly with an authority; they wrote saying:

> the “FOI inbox” link didn’t work. 

I suspect that's related to this issue.

**Comment by garethrees** [comment] 2018-05-30 09:39
I'm going to close this as a duplicate of https://github.com/mysociety/alaveteli/issues/10. Its close enough in nature that we can discuss alternative approaches in https://github.com/mysociety/alaveteli/issues/10.

**Closed by garethrees** 2018-05-30 09:39 UTC
Labels: 0 - backlog, f:redaction, f:request-analysis, improvement, t:design, user-experience, x:uk
