### ISSUE TITLE
Authorities disappeared when selecting new created language/locale

### ISSUE THREAD

**Issue by juanmartin** [mysociety/alaveteli#5903] opened 2020-10-01 01:51 UTC
Hi
I just created my own .po file for es_AR locale. Uploaded the file in ```locale/es_AR```.
Then selected the language in the general.yaml 
Everything working ok so far. My changes in the strings are reflected on the site.

The issue is that now all authorities have disappeared from the site.  I can find them through the requests previously made to the authority from the admin panel, meaning, they are not present in the Authorities list, but some requests had been made so I can click on the authority the request was sent to in order to access the authority's admin panel.
So, if I modify the authority by just clicking the save button, it is now back in the authorities list in the admin panel. *weird*.

Just made an update in the app.po file, and the issue didn't happen again, so I suspect that Alaveteli didn't like that I manually created a locale folder with its app.po and selected it as my new locale in the config.

Using Ubuntu 18.04

Thank you for this great and noble cause software!!
Cheers

**Comment by garethrees** [comment] 2020-10-01 09:56
> The issue is that now all authorities have disappeared from the site.

I expect this is because [`PUBLIC_BODY_LIST_FALLBACK_TO_DEFAULT_LOCALE`](https://alaveteli.org/docs/customising/config/#public_body_list_fallback_to_default_locale) is `false` by default. Essentially, you don't have translations for the bodies in the new locale so we don't try to display them.

> So, if I modify the authority by just clicking the save button, it is now back in the authorities list in the admin panel. _weird_.

This does indeed sound a little strange. If you've changed or removed the default locale, I expect what has happened is that there's no translation for the default (which is used in the admin UI), but by saving you create a translation record in the new default.

> Thank you for this great and noble cause software!!

Thanks for the kind words! I'm going to close this as you seem to have resolved the issue, but thanks for letting us know as its something we'll look out for next time we're setting up a site ourselves. Maybe we'll find the cause and get it fixed!

**Closed by garethrees** 2020-10-01 09:56 UTC
