### ISSUE TITLE
Admin debug page broken links

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/alaveteli#7064] opened 2022-06-01 22:40 UTC
On the [admin debug page](https://www.whatdotheyknow.com/admin/debug), the links to "Alaveteli branch" and "Alaveteli commit" are broken.  For example, the commit link takes you to [`https://github.com//tree/6ca4aaad6a01d93e016ab36ed9f97917f8a3502b`](https://github.com//tree/6ca4aaad6a01d93e016ab36ed9f97917f8a3502b), when (I think) it should be [`https://github.com/mysociety/alaveteli/commit/6ca4aaad6a01d93e016ab36ed9f97917f8a3502b`](https://github.com/mysociety/alaveteli/commit/6ca4aaad6a01d93e016ab36ed9f97917f8a3502b).

**Comment by mdeuk** [comment] 2022-06-01 23:02
Duplicate of https://github.com/mysociety/alaveteli/issues/5860#issuecomment-671812175

**Closed by mdeuk** 2022-06-01 23:02 UTC
Labels: x:uk, bug, f:admin
