### ISSUE TITLE
controllers/attachments_controller transient spec failure

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6474] opened 2021-08-12 08:19 UTC
Same seed as https://github.com/mysociety/alaveteli/issues/4635 but different failures:

```
Failures:

  1) AttachmentsController GET show with project_id params and logged in project member passes project to current ability
     Failure/Error:
       expect(Ability).to receive(:new).with(user, project: project).
         and_call_original

       (Ability (class)).new(#<User id: 1956, email: "person1955@example.com", name: "Pro User 265", hashed_password: "$2a$04$nd3R... 0, info_request_batches_count: 0, daily_summary_hour: 23, daily_summary_minute: 15, closed_at: nil>, {:project=>#<Project id: 513, title: "Important FOI Project", briefing: "<p>Please help analyse these...ests</p>", created_at: "2021-08-12 07:39:49", updated_at: "2021-08-12 07:39:49", invite_token: nil>})
           expected: 1 time with arguments: (#<User id: 1956, email: "person1955@example.com", name: "Pro User 265", hashed_password: "$2a$04$nd3R... 0, info_request_batches_count: 0, daily_summary_hour: 23, daily_summary_minute: 15, closed_at: nil>, {:project=>#<Project id: 513, title: "Important FOI Project", briefing: "<p>Please help analyse these...ests</p>", created_at: "2021-08-12 07:39:49", updated_at: "2021-08-12 07:39:49", invite_token: nil>})
           received: 0 times
     # ./spec/controllers/attachments_controller_spec.rb:213:in `block (4 levels) in <top (required)>'
     # /home/vagrant/bundle/ruby/2.7.0/gems/webmock-3.13.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  2) AttachmentsController GET show with project_id params and logged in non project member does not pass project to current ability
     Failure/Error:
       expect(Ability).to receive(:new).with(user, project: nil).
         and_call_original

       (Ability (class)).new(#<User id: 1961, email: "person1960@example.com", name: "Example User 1578", hashed_password: "$2a$04... 0, info_request_batches_count: 0, daily_summary_hour: 18, daily_summary_minute: 54, closed_at: nil>, {:project=>nil})
           expected: 1 time with arguments: (#<User id: 1961, email: "person1960@example.com", name: "Example User 1578", hashed_password: "$2a$04... 0, info_request_batches_count: 0, daily_summary_hour: 18, daily_summary_minute: 54, closed_at: nil>, {:project=>nil})
           received: 0 times
     # ./spec/controllers/attachments_controller_spec.rb:234:in `block (4 levels) in <top (required)>'
     # /home/vagrant/bundle/ruby/2.7.0/gems/webmock-3.13.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

Finished in 37 minutes 13 seconds (files took 29.24 seconds to load)
7045 examples, 2 failures, 5 pending

Failed examples:

rspec ./spec/controllers/attachments_controller_spec.rb:212 # AttachmentsController GET show with project_id params and logged in project member passes project to current ability
rspec ./spec/controllers/attachments_controller_spec.rb:233 # AttachmentsController GET show with project_id params and logged in non project member does not pass project to current ability

Randomized with seed 19901
```

**Comment by gbp** [comment] 2021-08-12 08:21
Duplicate of https://github.com/mysociety/alaveteli/issues/6436

**Closed by gbp** 2021-08-12 08:21 UTC
Labels: bug, f:test-suite
