### ISSUE TITLE
special tags for public bodies: "defunct", "signpost"

### ISSUE THREAD

**Issue by confirmordeny** [mysociety/alaveteli#414] opened 2012-02-05 10:30 UTC
http://www.whatdotheyknow.com/body/list/defunct - Defunct is a special tag and it would make sense for authorities tagged as defunct not to be listed on "Find missing FOI email for these public authorities (try phoning!)".

If we had unlimited resources which we don't I would suggest that we would have special tags as follows:

---

`refusedtoprovideemail`  - for authorities that simply refuse to provide an email address (e.g. http://www.whatdotheyknow.com/body/the_adjudicators_office),

not to be listed on "Find missing FOI email for these public authorities (try phoning!)"

---

`signpost` - for authority pages whose main current function is to point to another page (e.g. http://www.whatdotheyknow.com/body/alcuin_college)

not to be listed on "Find missing FOI email for these public authorities (try phoning!)"
stops new requests, allows follow ups (until email address is removed)

---

`recentdefunct` where authority has ceased to exist in last six months

not to be listed on "Find missing FOI email for these public authorities (try phoning!)"
stops new requests, allows follow ups

---

`defunct`  where authority has ceased to exist

not to be listed on "Find missing FOI email for these public authorities (try phoning!)"
stops new requests, stops follow ups

---

**Comment by schlos** [comment] 2020-12-23 20:48
"Defunct is a special tag and it would make sense for authorities tagged as defunct not to be listed on 'Find missing FOI email for these public authorities (try phoning!)'." -  is similar to another issue https://github.com/mysociety/alaveteli/issues/1577

**Comment by garethrees** [comment] 2021-01-05 10:52
> Defunct is a special tag and it would make sense for authorities tagged as defunct not to be listed on "Find missing FOI email for these public authorities (try phoning!)".

This part is fixed by https://github.com/mysociety/alaveteli/issues/1577.

The rest of the issue is a suggestion of extra special tags.

**Closed as completed** 2022-05-17 14:25 UTC
Labels: x:volunteer, admin-easier, f:authorities, improvement
