### ISSUE TITLE
Make request confirmation links expire once used

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#5949] opened 2020-11-04 11:35 UTC
One way duplicate requests are made is by users repeatedly clicking on confirmation links / using confirmation links as ways to find their request again and log into the site. 

Example correspondence from user:

>It appears that every time I log into the WhatDoTheyKnow website and look at my current request with [public body] it duplicates itself.

This wouldn't be as much of a problem if the duplicate requests were being caught, but there is a bug with that system, reported as issue #4160 

This is an alternative approach to addressing the problem of duplicated requests.

**Comment by mdeuk** [comment] 2020-11-20 07:28
I got caught by this one today 😔.

After verifying user 216290's account I made an error when clicking on the second verification link, which caused Safari to download the page (rather than display the right click context menu)… unbeknown to me, this had sent the request - meaning when I did it properly, we ended up with an uncaught duplicate.

**Comment by MattK1234** [comment] 2020-12-01 22:17
This gets a definite +1 from me as having to deal with the duplicates caused by this takes up admin time.

**Comment by RichardTaylor** [comment] 2020-12-02 12:59
Administrators clicking the link shouldn't result in request being sent.

[I don't know if that's a feature suggestion or a bug report.]

**Comment by RichardTaylor** [comment] 2021-02-16 14:02
+1 Still causing admin work

**Comment by garethrees** [comment] 2021-09-28 08:45
Will be easier to resolve this after https://github.com/mysociety/alaveteli/pull/6512.

**Comment by garethrees** [comment] 2023-09-28 15:21
Duplicate of https://github.com/mysociety/alaveteli/issues/4386

**Closed by garethrees** 2023-09-28 15:21 UTC
Labels: x:uk, easier-admin, f:request-creation
