### ISSUE TITLE
Malformed zip files

### ISSUE THREAD

**Issue by rubeycubey** [mysociety/alaveteli#5431] opened 2019-10-26 07:15 UTC
First reported here:
https://sourceforge.net/p/sevenzip/bugs/2230/

> The attached file is one of many zip files generated on the site www.righttoknow.org.au (which is based on (https://alaveteli.org). 7-zip is unable to open these zip files. However the unzip utility on Linux (Info-ZIP) and the WiZ utility from http://infozip.sourceforge.net/ are both able to open these zip files. The test option in these utilities also indicate the zip files are OK. Some other programs such Winzip are also unable to open zips from the site.

[rainbow_flags.zip](https://github.com/mysociety/alaveteli/files/3774547/rainbow_flags.zip)

7-zip developer responded:

> Extract that archive with Info-ZIP.
> Then look file sizes of extracted files.
> Then look file sizes in archive with Info-ZIP.
> Compare these sizes.
> Probably sizes stored in zip archive are incorrect.
> 
> So you can report about that problem to source: righttoknow.org.au

**Comment by garethrees** [comment] 2019-10-28 10:20
Thanks for reporting. Do you have a URL to the FOI request on http://www.righttoknow.org.au/ where the zip was downloaded?

**Comment by rubeycubey** [comment] 2019-10-28 10:26
That particular zip file is at the bottom of this page:
https://www.righttoknow.org.au/request/rainbow_flags#incoming-8901

However, the problem appears to occur with every zip file generated by that site.

**Comment by garethrees** [comment] 2019-10-28 10:36
It looks like this is a duplicate of https://github.com/mysociety/alaveteli/issues/4161.

We fixed https://github.com/mysociety/alaveteli/issues/4161 in https://github.com/mysociety/alaveteli/pull/4224, but http://www.righttoknow.org.au/ hasn't upgraded to a new enough release to get the fix.

Your best bet is to note this issue to them via http://www.righttoknow.org.au/help/contact.

I was able to extract the zip using Archive Utility on macOS, so maybe try an alternative to 7-Zip until they manage to upgrade.

**Closed by garethrees** 2019-10-28 10:36 UTC
Labels: bug, f:request-analysis, x:australia

**Comment by rubeycubey** [comment] 2019-10-28 10:39
Thank you.
