### ISSUE TITLE
Deter requests for email addresses

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6114] opened 2021-02-13 16:33 UTC
The system automatically redacts email addresses from responses. 

Users should be warned about this when making requests for contact details.  Administrators might not have the resources to unredact contact details if they are released. 

See also #10 and #3033 which might be preferable to address  

Addressing this issue might reduce the number/fraction of requests made via the service - and therefore be acting contrary to the aims of services running Alaveteli.

**Comment by mdeuk** [comment] 2021-02-13 16:39
+1, we've dealt with at least six requests in the WDTK team mailbox for this in the last few days alone.

I ponder if it might be possible to carry out reversible redaction, whereby the system rule will be overriden if the user completes a verification task, e.g. a captcha (similar to the method we use when users seek to view the address we use to send messages to a public body).

It's worth noting that captcha tasks are not always accessible, so we need to take care here to ensure that there is an accessible method for our users who may use assistive technology.

There are no doubt some challenges to doing that however, but it'd be good to see #3033 implemented.

**Comment by HelenWDTK** [comment] 2023-12-14 09:05
+1 This is still a major issue and the cause of a lot of support mail, particularly from commercial users.

**Comment by garethrees** [comment] 2024-11-22 11:43
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.

**Closed by garethrees** 2024-11-22 11:43 UTC
Labels: x:uk, f:request-creation, improvement, reduce-admin
