### ISSUE TITLE
Can't download CSV of authorities

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#3983] opened 2017-05-12 23:32 UTC
The link "List of all authorities (CSV)" on https://www.whatdotheyknow.com/body/list/all doesn't work - suspect similar scaling issue. https://www.whatdotheyknow.com/body/all-authorities.csv returns 502.

**Comment by lizconlan** [comment] 2017-05-22 13:27
Part  of #4007

**Comment by lizconlan** [comment] 2017-05-22 13:31
Timing out, I'm currently getting a 504 for this

**Comment by garethrees** [comment] 2018-08-09 08:55
This now works, probably because we're on new hardware.

I expect this will break again at some point, but until then I'm going to close this.

If it does break, I think we'd need to move to serving a cached copy (generated every IDK, 6 hours?) as the code that currently generates it doesn't have any obvious performance warning signs.

**Comment by garethrees** [comment] 2022-07-14 08:47
Reopening based on https://github.com/mysociety/whatdotheyknow-theme/issues/1283. The issue isn't WDTK specific, but WDTK suffers most due to having a large number of authorities. France also have [50k](https://madada.fr/body/list/all)+.

**Comment by MattK1234** [comment] 2022-07-16 11:55
It took me around 6-8 attempts to download the all-authorities csv on WDTK the other evening.

**Comment by ajparsons** [comment] 2022-07-18 14:38
I'm trying doing some data work over the top of this export. This file should stay in sync with this file daily:

https://mysociety.github.io/wdtk_authorities_list/datasets/whatdotheyknow_authorities_dataset/latest

(Haven't locked the exact structure in yet, but should be faster to download)

**Comment by garethrees** [comment] 2022-09-09 08:58
This reminded me that I came across [this post about streaming CSV files](https://medium.com/table-xi/stream-csv-files-in-rails-because-you-can-46c212159ab7) while looking at https://github.com/mysociety/alaveteli/issues/7027#issuecomment-1225364665. Doesn't seem a million miles away from what we're doing already and, if it works, would avoid needing to do extra configuration and we'd have fresher data?

**Comment by garethrees** [comment] 2022-09-16 09:02
Have we got cache headers set on this? Could cache it via varnish so that re-users don't have to faff with cron.

If we did want to go for a file-based cache, it would be nicer not to have to set up a crontab. We could stat the cached file, serve it directly if < N hours old, otherwise regenerate and recache.

**Comment by gbp** [comment] 2022-09-16 09:23
No cache headers at present. With a file-based cache we're now (temporarily?) using its not really necessary to cache twice.

If we go back to generating on the fly then it isn't going to fix the issue as the request is never complete before the response closes so it won't ever get cached.

I'm not too concern about adding an extra cronjob, ultimately these should be replaced by https://github.com/mysociety/alaveteli/issues/1240

We should investigate:
1. streaming the response
2. speeding up the response - did adding notes model cause extra queries?
3. ...?

**Closed** 2022-09-16 09:29 UTC
Labels: x:uk, bug, performance, f:authorities, x:france
