### ISSUE TITLE
Survey Monkey

### ISSUE THREAD

**Issue by confirmordeny** [mysociety/alaveteli#532] opened 2012-07-22 19:58 UTC
Is there a way to stop survey requests etc requiring requests to be reclassified - example: http://www.whatdotheyknow.com/request/truth_behind_muslim_doctors_not

**Comment by garethrees** [comment] 2020-11-24 22:05
Closing as a duplicate of https://github.com/mysociety/alaveteli/issues/2342

**Closed by garethrees** 2020-11-24 22:05 UTC
Labels: backlog, easier-admin, enhancement, f:request-management, x:volunteer
