### ISSUE TITLE
Error causes requests page to stop working in admin interface

### ISSUE THREAD

**Issue by gavinrozzi** [mysociety/alaveteli#5112] opened 2019-02-23 02:45 UTC
It appears a request is causing Alaveteli to throw an error whenever an administrator attempts to visit the "Requests" page in the admin interface. Here is the portion of our logs from when the error occurred:

```
[2019-02-22T18:54:07.745559 #24233] FATAL -- : 
RuntimeError (internal error, last_event_forming_initial_request gets nil for request 4200 outgoing messages count 1 all events: --- []
):
  app/models/info_request.rb:1057:in `last_event_forming_initial_request'
  app/models/info_request.rb:1127:in `calculate_date_initial_request_last_sent_at'
  app/models/info_request.rb:1121:in `date_initial_request_last_sent_at'
  app/models/concerns/admin_column.rb:26:in `block in for_admin_column'
  app/models/concerns/admin_column.rb:24:in `each'
  app/models/concerns/admin_column.rb:24:in `for_admin_column'
  app/views/admin_request/_some_requests.html.erb:17:in `block in _app_views_admin_request__some_requests_html_erb__1480648581990963533_47417609022440'
  app/views/admin_request/_some_requests.html.erb:2:in `_app_views_admin_request__some_requests_html_erb__1480648581990963533_47417609022440'
  app/views/admin_request/index.html.erb:10:in `_app_views_admin_request_index_html_erb__870940833306495274_47417609017020'
  app/controllers/application_controller.rb:120:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by garethrees** [comment] 2019-02-25 14:43
Ah, my favourite cryptic error in Alaveteli.

The gist is that an outgoing message failed to send – you can manually resend it through the console https://github.com/mysociety/alaveteli/wiki/Resending-Failed-Outgoing-Messages

Some related issues:

* https://github.com/mysociety/alaveteli/issues/2578
* https://github.com/mysociety/alaveteli/issues/1125

Let us know if that helps you resolve this issue.

**Comment by gavinrozzi** [comment] 2019-02-25 16:14
Thanks, Gareth, I’ll give this a try.

**Comment by garethrees** [comment] 2019-03-11 16:07
Going to close this as a duplicate of https://github.com/mysociety/alaveteli/issues/2578.

**Closed by garethrees** 2019-03-11 16:07 UTC
