### ISSUE TITLE
Reveal email addresses in incoming emails to requesters

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#2900] opened 2015-11-12 19:50 UTC
We get a reasonable flow of people asking us to reveal email addresses that Alaveteli has obfuscated in incoming emails in response to requests. 

A suggestion: make email addresses revealable to requesters when they are logged in to their account (not to other people whether logged in or not, to avoid spam)

I suspect that coding this would be non-trivial, but it's a "would be nice to have"

**Comment by RichardTaylor** [comment] 2015-11-12 23:45
The use-case here tends to be when a requestor has asked a series of public bodies something like: >Please let me have the email address of the person responsible for buying widgets for your organisation

The user is annoyed when the replies come back with the emails redacted and administrators are then asked to extract them, which is time consuming. 

Turning off email redaction on a per-user basis would help a lot. 

If this is implemented the request addresses should remain hidden. 

I'll close this as it is a pretty much a duplicate of #10

**Closed by RichardTaylor** 2015-11-12 23:45 UTC
