### ISSUE TITLE
Offer form for suggesting changes to public body database beyond just the request address

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6085] opened 2021-01-29 12:43 UTC
Currently the system has a link on public body pages for: "Ask us to update FOI email" which links to a form for submitting a new email address. 

This approach could be extended to cover other edits public bodies themselves, or others, might wish to suggest eg. a name change, or a change to the public notes, home page etc. 

Ticket prompted by a public body using the "Ask us to update FOI email"  to alert WhatDoTheyKnow to the fact their name had changed.

**Comment by garethrees** [comment] 2022-02-11 17:47
I think this is essentially a duplicate of https://github.com/mysociety/alaveteli/issues/4686?

**Closed by garethrees** 2022-02-11 17:47 UTC
Labels: x:uk, f:authorities, improvement
