### ISSUE TITLE
Uncaught duplicates

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#4235] opened 2017-09-17 20:31 UTC
A user sent the same request to the same body 10 times, which makes me think the duplicate catcher code isn't working.

https://www.whatdotheyknow.com/request/all_discipliners_for_wilful_inte
https://www.whatdotheyknow.com/request/all_discipliners_for_wilful_inte_2
https://www.whatdotheyknow.com/request/all_discipliners_for_wilful_inte_3
https://www.whatdotheyknow.com/request/all_discipliners_for_wilful_inte_4
https://www.whatdotheyknow.com/request/all_discipliners_for_wilful_inte_5
https://www.whatdotheyknow.com/request/all_discipliners_for_wilful_inte_6
https://www.whatdotheyknow.com/request/all_discipliners_for_wilful_inte_7
https://www.whatdotheyknow.com/request/all_discipliners_for_wilful_inte_8
https://www.whatdotheyknow.com/request/all_discipliners_for_wilful_inte_9
https://www.whatdotheyknow.com/request/all_discipliners_for_wilful_inte_10

**Comment by garethrees** [comment] 2017-09-18 08:56
We did find an issue with this in https://github.com/mysociety/alaveteli/issues/4235 – closing this issue as a duplicate of https://github.com/mysociety/alaveteli/issues/4235 and we'll get to a fix as soon as we can!

**Closed by garethrees** 2017-09-18 08:56 UTC

**Comment by lizconlan** [comment] 2017-09-18 09:02
duplicate of #4160?

**Comment by garethrees** [comment] 2017-09-18 09:03
oops yes!
