### ISSUE TITLE
Make it easy to switch back to being logged in as admin user after using the "login as" feature to login as another user

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6307] opened 2021-06-11 10:16 UTC
Currently if an administrator uses the "login as" feature on a user admin page to login as another user and then wants to return to their own user account they need to logout and back in. 

Recently on WhatDoTheyKnow greater use has been made of a WhatDoTheyKnow account, being able to easily switch between that account and an individual admin account would be particularly useful, and implementing this general feature would be one way of achieving that. 

See related discussion at:

https://github.com/mysociety/alaveteli/issues/306#issuecomment-3821128

**Comment by MattK1234** [comment] 2021-06-20 19:09
Appears to be a duplicate of #1785 so closing this one.

**Closed by MattK1234** 2021-06-20 19:09 UTC
Labels: easier-admin, f:admin, improvement, x:uk
