### ISSUE TITLE
Redesign 'write a reply' interface

### ISSUE THREAD

**Issue by hsenag** [mysociety/alaveteli#1049] opened 2013-08-19 21:54 UTC
It's not very easy to understand where a reply you go will be sent to.

Firstly, people can miss the green box listing the alternatives altogether, which is probably fine most of the time as the default will be ok.

However even if you do look at the box, the text you get for each possible target address is often confusing because it depends on the "real name" part of the incoming email addresses.

One option for making it clearer might be to actually make the email addresses explicit, though that goes somewhat against our current policy of keeping those addresses hidden. Another might be for the choice of reply targets to make explicit which messages they relate to, or to go back to the old UI of being able to write a reply on each message.

See also #778 (and #426 if it's still relevant).

**Comment by ChristopherWhitmey** [comment] 2015-11-30 19:11
In a recent FOI I was told: "it would be helpful if future correspondence is directed to myself, as your request was addressed to the 'Ministers' email box and this tends to delay matters while the correct part of the department is located.".

Hovering over the purple incoming links I saw that:
693027=     DfE Ministerial and Public Communications Division on 150814
729003=     SB on 151105
735826=     SB  on 151120

Checking SB's previous link refs I see that each one is unique. From the above it appears that the SB link on the Write a Reply page is not the latest one. But I accept that the real email behind both might be the same!

I wonder if the following rubric on the 'Write a Reply' page might help:
e.g.  Department for Education  Hovering over this link the last number is the last number on the link of an incoming message. Use this link to reply to that person.

Or to save having it after each link a rubric at the top:

To help ensure you reply to the person who sent the message under reply hover over each link in turn. The last number is the last number on the link of an incoming message from a particular email address. Use this link to reply to that person.

I suppose a more complex way would be to code the programme so that the name of the signatory was extracted from the message and put after the reply link !

Is it possible to amend the Write a Reply page to make a very friendly website even friendlier please?

**Comment by olineham** [comment] 2016-11-04 03:08
A further illustration (from FYI.org.nz) of how this can be a real usability problem:

![0](https://cloud.githubusercontent.com/assets/523321/19993204/c7925004-a2a8-11e6-9827-e8d20a69cbb6.png)

See also #10 regarding letting users see email addresses under certain circumstances.

**Comment by garethrees** [comment] 2018-07-17 11:16
Closing as a duplicate of https://github.com/mysociety/alaveteli/issues/4354, as that one has more recent thinking.

**Closed by garethrees** 2018-07-17 11:16 UTC
Labels: 0 - backlog, f:request-management, improvement, t:design, user-experience, x:new-zealand, x:uk
