### ISSUE TITLE
Consider subject lines and content of system generated emails which become external correspondence threads

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#4982] opened 2018-11-30 03:30 UTC
When an administrator responds to a correspondent who has marked a request for admin attention by replying to a system generated email the subject line isn't ideal for external correspondence, it is:

>Re: FOI response requires admin ([request status]) - [Subject]

nor would we ideally quote a message containing an administration URL in external correspondence - which is what happens when administrators reply to one of these system generated messages quoting the original message which contains an administration link. 

Related: #4961  "Improve email threading when responding to change requests" 
Perhaps best solved by implementing: #419 "Bring user support and takedown requests within the system"

I'm expecting this to be promptly marked backlog, and I'm happy with that, it's not important, but I think it's a genuine issue that ideally would be addressed.

**Comment by RichardTaylor** [comment] 2018-12-01 00:20
Related:  #516 - which I think is about making these subject lines clearer for administrators and I'll try again linking #4961

**Comment by garethrees** [comment] 2018-12-03 12:31
I think this is essentially a duplicate of https://github.com/mysociety/alaveteli/issues/516.

> nor would we ideally quote a message containing an administration URL in external correspondence

I would make this its own issue, but there's no way we can solve this without #419.

Going to close this as I don't think there's any direct action we can take that isn't already covered elsewhere.

**Closed by garethrees** 2018-12-03 12:31 UTC
Labels: user-experience
