### ISSUE TITLE
Requesters should be able to see their requests without censorship

### ISSUE THREAD

**Issue by bjh21** [mysociety/alaveteli#471] opened 2012-04-08 23:54 UTC
When a request is censored, either by censor rules or by direct editing of outgoing messages, it would be helpful if the requester could see the original.  This would be helpful, for instance, if there were parts of a request that we were unwilling to publish but the requester wanted to complain about its handling to the ICO.

For censor rules, there should be a flag on the rule indicating whether it applies to the requester (since sometimes we might to censor incoming messages for them too).  I don't think any such thing is necessary for editing outgoing messages.

**Comment by garethrees** [comment] 2019-10-30 10:21
Duplicate of https://github.com/mysociety/alaveteli/issues/218

**Closed by garethrees** 2019-10-30 10:21 UTC
Labels: 0 - backlog, enhancement, f:request-analysis, user-experience
