### ISSUE TITLE
Admin form labels incorrect

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#5706] opened 2020-06-05 09:47 UTC
![Screenshot 2020-06-05 at 10 43 24](https://user-images.githubusercontent.com/5426/83862363-5aed3880-a711-11ea-8d79-ab8822dac957.png)

**Comment by garethrees** [comment] 2020-06-05 11:22
Duplicate of https://github.com/mysociety/alaveteli/issues/5413

**Closed by garethrees** 2020-06-05 11:22 UTC
Labels: bug, f:admin
