### ISSUE TITLE
502 errors on classifying requests as successful

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#4012] opened 2017-05-29 18:02 UTC
I thought this was just Pro accounts / me, but I am getting reports that this is happening for other users too.

"I have been trying to update my status on this yesterday and today but when I submit it, it then comes up with a blank page saying 502 gateway error, therefore I am unable to carry on.  Can you suggest anything please?  I have received all the information I requested and was pressing that relevant button."

https://www.whatdotheyknow.com/request/vaginal_tape_used_in_surgery

**Comment by lizconlan** [comment] 2017-05-30 09:15
duplicate of #3922

**Comment by lizconlan** [comment] 2017-05-30 09:15
(useful duplicate, carry on!)

**Closed by lizconlan** 2017-05-30 09:15 UTC
