### ISSUE TITLE
Prompt users to find updated contact details when reporting a delivery error

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6520] opened 2021-09-15 08:50 UTC
We want to encourage reporting of delivery errors (https://github.com/mysociety/alaveteli/issues/5640), but at the same time we should ask the community for help in resolving them.

This usually means finding an updated email address for the authority, which can be submitted through Alaveteli itself. We should build this into the reporting flow.

See delivery error → report → report gets created → user lands on an interstitial page asking them to check the address and submit a new one if it's different

**Comment by RichardTaylor** [comment] 2021-09-15 09:15
Closing as duplicate of https://github.com/mysociety/alaveteli/issues/1782

**Closed by RichardTaylor** 2021-09-15 09:15 UTC
Labels: x:uk, f:authorities, enhancement, reduce-admin

**Comment by garethrees** [comment] 2021-09-15 09:29
Ha, I was convinced we'd ticketed this previously 🤦
