### ISSUE TITLE
Consider handling of bodies using multiple domains

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/alaveteli#7037] opened 2022-05-18 19:20 UTC
Some bodies have multiple alias domains, where an email could come from either `foi@example.com` or `foi@xm.pl`, where sending an email to either would lead to the same place.

I'm not sure whether this is common or problematic enough. Potential problems:

- Domains for responding by upload: user is presented with the domain required, so they could change their account to the alias email.
- Requests open to `authority_only`: would just be inconvenient re-opening a request where it could have been avoided.

Some bodies might have[^noex] domains which are not aliases.

[^noex]: I have no current examples, but am aware of historic ones where a body was transferring in a protracted manner from one domain to another.

**Comment by garethrees** [comment] 2022-05-19 08:30
Closing as a duplicate of https://github.com/mysociety/alaveteli/issues/455.

**Closed by garethrees** 2022-05-19 08:30 UTC
