### ISSUE TITLE
Stronger warnings on preview for suspected personal correspondence

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#4583] opened 2018-03-23 13:45 UTC
The software already gives warnings to users including postcodes or email addresses in requests when they "preview" them. 

Could these be strengthened and expanded to include national insurance numbers, phone numbers, and perhaps even common phrases found in correspondence about individual circumstances?

People misusing the service to send personal correspondence create work for site administrators; and sometimes people accidentally publish private information about themselves. 

Ticket raised following discussion on catch-up call.

**Comment by garethrees** [comment] 2018-11-21 18:06
I think this is essentially a duplicate of https://github.com/mysociety/alaveteli/issues/3515

**Closed by garethrees** 2018-11-21 18:06 UTC
Labels: 0 - backlog, easier-admin, f:admin, f:request-creation, improvement, prevent-issue, user-experience, x:uk, x:volunteer
