### ISSUE TITLE
Show all the information via an admin email in the relevant admin section

### ISSUE THREAD

**Issue by benrfairless** [mysociety/alaveteli#6113] opened 2021-02-13 02:32 UTC
When a user makes a request (such as to change the authority details or to report a request) there are more details sent through via email then are shown in the admin portal.

This makes it difficult if something happens to the original email that was sent to us.

**Comment by garethrees** [comment] 2021-02-15 09:52
Linking as a specific case of https://github.com/mysociety/alaveteli/issues/419 and closing as a duplicate of https://github.com/mysociety/alaveteli/issues/5368.

**Closed by garethrees** 2021-02-15 09:52 UTC
