### ISSUE TITLE
Show requester_only requests on user profile page to admins

### ISSUE THREAD

**Issue by henare** [mysociety/alaveteli#2862] opened 2015-10-22 04:01 UTC
I was just looking for a request someone made that had been set to requester_only. To do this I found the person on the site and was surprised when there were no requests on their profile page.

I had to go into the backend to find the request. I think these requests should show up on the user profile page when you're logged in as an admin.

**Comment by RichardTaylor** [comment] 2021-05-27 18:37
requester_only requests should also appear to users on their own profile pages, the issue for this is: https://github.com/mysociety/alaveteli/issues/843

**Comment by garethrees** [comment] 2021-05-28 10:51
Closing as a duplicate of https://github.com/mysociety/alaveteli/issues/843.

**Closed by garethrees** 2021-05-28 10:51 UTC
Labels: backlog, easier-admin, f:admin, f:user-profiles, improvement, x:australia
